### ISSUE TITLE
get icon by id is not working

### ISSUE THREAD

**Issue by t3space** [rosshettel/the-noun-project#10]
Hello, Thanks for this nice library,
I am using this for my project and I needed to get an icon from nounproject by id,
I used this:
```

nounProject.getIconById(id, (err, data) => {
    if (!err) {
      res.send(data);
    } else {
      res.send(err.message);
    }
  });
```
the data is not coming.
Please help me with this problem.

Thanks,

**Comment by rosshettel** [comment]
Hey there,

From the code you posted nothing looks incorrect, you're calling things correctly. There could be other issues somewhere, like your API key not working or something else in your program not set up correctly. Might need to post more info or code examples to help track the issue down.

**Comment by andsilver** [comment]
Hello @rosshettel , sorry for late.
I think the problem is coming from other point.
When I test the api to get icons by term on api explorer (https://api.thenounproject.com/explorer#!/icons/getIconsByTerm) and on my local using the library, the results were different each other.

Could you please try to test on both api explorer and on nodejs? The term was 'a'.
nounProject.getIconsByTerm('a', callback)

Thanks.

**Comment by andsilver** [comment]
sorry it was my fault. I missed the options, It is working fine.
